### ISSUE TITLE
[Bug] Wattage and Temperature displays 0W/0C in v0.4.4

### ISSUE THREAD

**Issue by MinecraftDocker** [IceWhaleTech/CasaOS#1208]
My Wattage/Temperature display in CasaOS is stuck at 0W/0C permanently. 
This is running on a laptop with hardware is as follows:
    Intel i7 640LM
    6Gb RAM
    250Gb HDD

1. Update to v0.4.4
2. Reboot and open the WebGUI

**Expected behavior**
I expected it to display real-time info on what my hardware is doing.

![Screenshot 2023-06-24 134753](https://github.com/IceWhaleTech/CasaOS/assets/137648057/0312a095-40d7-4169-bd23-f45ac8a66d18)

**Desktop (This is the computer I am accessing CasaOS on):**
 - OS: Windows 11
 - Browser: Brave
 - Version: Version 1.52.126 Chromium: 114.0.5735.133 (Official Build) (64-bit)

**Logs**

run following command to collect corresponding logs:
Do you want the whole log, or just certain parts?
```bash
sudo journalctl -xef -u casaos-gateway
sudo journalctl -xef -u casaos-user-service
sudo journalctl -xef -u casaos-local-storage
sudo journalctl -xef -u casaos.service
```

**Additional context**
I am running this on top of OMV6, or Debian 11 (Bullseye)

**Comment by pokurt** [comment]
its happening on 0.4.3 as well. visit your casaos dashboard via IP address and it should be fixed. i dont know a way i can get ti to work with local url yet.

**Comment by MinecraftDocker** [comment]
Visiting the servers local IP address instead of the host.local does not fix the problem for me. Still getting 0W/0C while running Handbrake container. I am using the default Port 80 for the WebUI.

**Comment by LinkLeong** [comment]
1. What system is casaos installed on?
2. The place where we get the power consumption is `/sys/class/powercap/intel-rapl/intel-rapl:0/energy_uj` and `/sys/class/powercap/intel-rapl/intel-rapl:0/energy_uj`, you can check these two files
3. The way we get the temperature is `/sys/devices/virtual/thermal/thermal_zone{number}/temp` , the way to determine the number is to have a type file at the same level as temp, it needs to be "x86_pkg_temp", "cpu", "CPU". "soc" one of these values, then you can assume that it is the temperature. The code is as follows
![image](https://github.com/IceWhaleTech/CasaOS/assets/13556972/2d847d22-4a02-4b9b-a25f-6c40725da42c)

**Comment by raller1028** [comment]
Can you try this command
` cat /sys/devices/virtual/thermal/thermal_zone*/type
 cat /sys/devices/virtual/thermal/thermal_zone*/temp`
![image](https://github.com/IceWhaleTech/CasaOS/assets/57336867/664a30f1-b5ee-453e-b20e-cc16e310dc83)

**Comment by pokurt** [comment]
https://github.com/IceWhaleTech/CasaOS/assets/43902347/fbb0cec2-5ad5-40d8-bd87-20676209a793

this lead me to think its a problem with pihole or built in firewall of the Operating System that is using casaOS service. i will take a look and keep you guys updated :)

**Comment by MinecraftDocker** [comment]
@raller1028
This is the output of the two commands.
![cattemp](https://github.com/IceWhaleTech/CasaOS/assets/137648057/2e3a3582-a160-4da8-83e3-11bdbfd92556)
![cattype](https://github.com/IceWhaleTech/CasaOS/assets/137648057/269e8419-941e-4e11-982f-1fc4615ce6d7)

@pokurt 
Accessing the Workbench from the IP vs the .local url doesn't change anything. Yes, I did close the tab and reopen it to switch.

**Comment by raller1028** [comment]
@MinecraftDocker According to your screenshot, we can see that you are getting the temperature from acpitz, but we only support type="x86_pkg_temp", "cpu", "CPU", "soc"

**Comment by LinkLeong** [comment]
> output.mp4 
> this lead me to think its a problem with pihole or built in firewall of the Operating System that is using casaOS service. i will take a look and keep you guys updated :)

Did you use nginx as a proxy? I tested it with nginx proxy manager and need to open websocket settings. 
![image](https://github.com/IceWhaleTech/CasaOS/assets/13556972/0eddccae-b2ed-4f6e-b833-a370ddaa9835)

**Comment by pokurt** [comment]
> > output.mp4
> > this lead me to think its a problem with pihole or built in firewall of the Operating System that is using casaOS service. i will take a look and keep you guys updated :)
> 
> Did you use nginx as a proxy? I tested it with nginx proxy manager and need to open websocket settings. ![image](https://user-images.githubusercontent.com/13556972/250482507-0eddccae-b2ed-4f6e-b833-a370ddaa9835.png)

this works well now. thank you @LinkLeong

**Comment by MinecraftDocker** [comment]
@raller1028 
How do I change the type from acpitz to a supported type?

**Comment by raller1028** [comment]
@MinecraftDocker  Sorry, we are unable to support acpitz types at this time, this is within the scope of cpu support

**Comment by MinecraftDocker** [comment]
OK, so what I am gathering is that my CPU is physically incompatible with this feature. Is this correct?
If so, my next comment will close this issue.

**Comment by LinkLeong** [comment]
@MinecraftDocker yes!

**Comment by MinecraftDocker** [comment]
Ok, thanks so much for helping!
Rather annoying that my hardware is incompatible, but hopefully this will help someone else.
