### ISSUE TITLE
[Bug] Clicking on a legacy app to import it does nothing

### ISSUE THREAD

**Issue by Bodyes26** [IceWhaleTech/CasaOS#1314]
**Describe the bug**

> When clicking on a legacy app that says "Import to CasaOS" it does nothing. On console there is this error:
```
@vue/cli-service/node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/@vue/cli-service/node_modules/vue-loader/lib??vue-loader-options:341 Error: Request failed with status code 404
    at createError (createError.js:16:15)
    at settle (settle.js:17:12)
    at XMLHttpRequest.onloadend (xhr.js:66:7)
```

**To Reproduce**

> Steps to reproduce the behavior:

1. Go to homepage
2. Click on any legacy app
3. Go to the browser console

**Expected behavior**

> A prompt to import the app? Idk really

**Desktop (please complete the following information):**

```
 - OS: [Ubuntu Server]
 - Browser [ARC Browser (Chromium)]
 - Version [v0.4.4.1]
```

**Comment by raller1028** [comment]
This has been fixed, could you please update v0.4.4-1 again via command line?
`curl -fsSL https://get.casaos.io/update/v0.4.4-1 | bash`

**Comment by Bodyes26** [comment]
When I try that code it gives me this error
```
- INFO Configuration CasaOS Addons
main: line 419: pushd: /tmp/casaos-installer/tmp.LhSwu09lwB: Permission denied
```

**Comment by Bodyes26** [comment]
Solved with uninstalling casaos with
`sudo casaos-uninstall`
and then this command
`curl -fsSL https://get.casaos.io/update/v0.4.4-1 | sudo bash`

**Comment by ZDStudios** [comment]
Wait but i'm on v0.4.13 and when i click on the app to install it it still does nothing? How to fix? I do not want to uninstall casaos tho?
