### ISSUE TITLE
[Feedback]Failed to load apps

### ISSUE THREAD

**Issue by nothingtocareabout** [IceWhaleTech/CasaOS#2443]
It is impossible to fix this error. I have tried all possible solution but CasaOS remains unable to load the apps making the computer useless. Any decent tutorial to fix it?

**Comment by x3llaz** [comment]
Quoted from onefish2 from another thread that worked on my Pi 5:
> A workaround without the need to downgrade docker version or portainer, which is to manually lower the minimum API version of docker:
> 
> systemctl edit docker.service
> 
> Add this part above the line ### Lines below this comment will be discarded:
> 
> [Service] Environment=DOCKER_MIN_API_VERSION=1.24
> 
> Save and exit systemctl restart docker

I'm surprised the CasaOS team still hasn't released an official fix for this.

**Comment by nothingtocareabout** [comment]
Thanks! I will try and come back to you.

**Comment by brandaolopes** [comment]
> Quoted from onefish2 from another thread that worked on my Pi 5:
> 
> > A workaround without the need to downgrade docker version or portainer, which is to manually lower the minimum API version of docker:
> > systemctl edit docker.service
> > Add this part above the line ### Lines below this comment will be discarded:
> > [Service] Environment=DOCKER_MIN_API_VERSION=1.24
> > Save and exit systemctl restart docker
> 
> I'm surprised the CasaOS team still hasn't released an official fix for this.

I've just tried this here in my Ubuntu 22.04 LTS - OrangePI 5 Max. But not successful

**Comment by unix1984** [comment]
> Quoted from onefish2 from another thread that worked on my Pi 5:
> 
> > A workaround without the need to downgrade docker version or portainer, which is to manually lower the minimum API version of docker:
> > systemctl edit docker.service
> > Add this part above the line ### Lines below this comment will be discarded:
> > [Service] Environment=DOCKER_MIN_API_VERSION=1.24
> > Save and exit systemctl restart docker
> 
> I'm surprised the CasaOS team still hasn't released an official fix for this.



Thanks, it works for me. The containers are now accessible again through the web interface.

+1

**Comment by Dev01-D** [comment]
Hi all!
Sorry for the long wait, with the help of Sabitech, the installation script has been fixed 🙂 , now you can just do a clean install or use the current installation script to fix the previous docker app not loading.
The new script has the following features:

    Install the latest available Docker engine instead of Docker 24.0.7
    Apply a Docker API compatibility override for newer Docker versions
    Allow CasaOS services and baked-in apps to work with modern Docker

Please rest assured that we will continue to improve user experience and working hard to ensure compatibility across multiple platforms.

**Comment by janesmoon** [comment]
Hello! Hello! Unfortunately, changing DOCKER_MIN_API_VERSION=1.24 did not solve the problem for me! I still only see the CasaOS basic app store and file icon! The dockers are not visible, even though they are working, and jellyfin, immch, etc. are available! The CasaOS version is v0.4.15! What could be the problem? I've been struggling with this for hours, but it won't load the dockers! Please help!
