### ISSUE TITLE
[Bug] Its been a month and still no fix? WTF!?

### ISSUE THREAD

**Issue by NaufalF22** [IceWhaleTech/CasaOS#2449]
<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/c6c1456d-c4cf-434d-9c97-507b7cbb1bf2" />

**Comment by owillems** [comment]
Hi @NaufalF22,

I understand your frustration — this issue has been affecting a lot of users, and waiting for a fix can definitely be annoying. Fortunately, there is a temporary workaround available in the discussion here: #2404. As Sonarta mentioned, downgrading Docker to a compatible version restores the ability to load apps until the CasaOS update is released.

I know it’s easy to get upset when things break, but negative or hostile comments don’t help the maintainers or the community. Most contributors here are volunteering their time, and constructive feedback makes it easier for everyone to work together and stay engaged.

Hopefully the fix will be merged soon. In the meantime, the workaround should keep your system running normally.

**Comment by manalshaikh** [comment]
From what I know, CasaOS has been abandoned in favor of their ZimaOS app. The new ZimaOS has paid tiers which casa didn't thus the abandonment.

**Comment by x3llaz** [comment]
> From what I know, CasaOS has been abandoned in favor of their ZimaOS app. The new ZimaOS has paid tiers which casa didn't thus the abandonment.

Seriously? Is there an official acknowledgement of this? If so, that's unfortunate. 😔 
I was wondering myself why is it taking so long for a simple problem to get an official fix. 
I didn't want to believe they would abandon CasaOS but this long delay makes it seem true.

**Comment by Dev01-D** [comment]
Hi all!
Sorry for the long wait, with the help of Sabitech, the installation script has been fixed 🙂 , now you can just do a clean install or use the current installation script to fix the previous docker app not loading.
The new script has the following features:

    Install the latest available Docker engine instead of Docker 24.0.7
    Apply a Docker API compatibility override for newer Docker versions
    Allow CasaOS services and baked-in apps to work with modern Docker

Please rest assured that we will continue to improve user experience and working hard to ensure compatibility across multiple platforms.

**Comment by x3llaz** [comment]
> Hi all! Sorry for the long wait, with the help of Sabitech, the installation script has been fixed 🙂 , now you can just do a clean install or use the current installation script to fix the previous docker app not loading. The new script has the following features:
> 
> ```
> Install the latest available Docker engine instead of Docker 24.0.7
> Apply a Docker API compatibility override for newer Docker versions
> Allow CasaOS services and baked-in apps to work with modern Docker
> ```
> 
> Please rest assured that we will continue to improve user experience and working hard to ensure compatibility across multiple platforms.

Is this fix only possible doing a clean install? I tried reinstalling over an existing installation and it didn't fix the problem. I had to edit docker.service and set minimum docker version to 1.24 to make apps load again. It would be nice to have an official fix for existing installations as this will make more sense.

That said, thank you for confirming the continued support for CasaOS!

**Comment by Sn0w3y** [comment]
GUYS !!!!

  Step 1: Add Docker API version to environment
  echo "DOCKER_API_VERSION=1.44" >> /etc/environment

  Step 2: Add to CasaOS service file
  sudo nano /etc/systemd/system/casaos.service
  Add under [Service]:
  Environment="DOCKER_API_VERSION=1.44"

  Step 3: Reload systemd
  sudo systemctl daemon-reload

  Step 4: Restart CasaOS services
  sudo systemctl restart casaos*

  Step 5: Verify
  source /etc/environment
  echo $DOCKER_API_VERSION
  Should output: 1.44


wtf...
