### ISSUE TITLE
Using Backspace when renaming file/folder will move the folder or file to the parent directory

### ISSUE THREAD

**Issue by AuthorShin** [IceWhaleTech/CasaOS#252]
When adding/renaming file or folder in casaos files in the test box if you want to use Backspace it will move the folder or file to the parent directory.

For example: in home/docker/image/edit-it.txt you want to rename it to edit.txt when you click on rename and the rename box showed up if you click on backspace on the keyboard to remove the -it part it will move the file to upper directories so it will be: home/docker/edit.txt

**Comment by JohnGuan** [comment]
This issue has been addressed in our recent development.

**Comment by AuthorShin** [comment]
I'm using ` v0.3.2 ` and the problem is still there.

**Comment by AuthorShin** [comment]
@JohnGuan @tigerinus 
I'm using ` v0.3.2 ` and the problem is still there.

**Comment by tigerinus** [comment]
@jerrykuku I can easily reproduce this bug on v0.3.2.1. Please take a look.

**Comment by LinkLeong** [comment]
Thank you for your feedback, we have solved the problem in v0.3.3, I will close the problem, if you have questions, please open a new issue
