### ISSUE TITLE
Sync your data issue. Not open popup.

### ISSUE THREAD

**Issue by chicato83** [IceWhaleTech/CasaOS#45]
**Describe the bug**
It does not show me the popup windows information to download the app and sync.
**To Reproduce**
1. Go to 'Sync your data'
2. Click on 'Go!.'
3. See error

**Expected behavior**
Open a popup windows with the information to download and install the app for sync
**Screenshots**
![nothing](https://user-images.githubusercontent.com/11451030/144699830-eeb2bfd6-f3de-4e05-ada9-17938d794db5.png)

**Desktop (please complete the following information):**
 - OS: [Linux Mint 20.22]
 - Browser [Brave - lasts, Firefox - lasts]
 - Version [casaOS 0.22]

**Additional context**
I tried it on my phone and open the windows popup, I don't know if the issue is because I am using Linux.

**Comment by LinkLeong** [comment]
We fixed this issue in v0.2.3, please check the verification

**Comment by chicato83** [comment]
I am on v0.2.3, and I still have the same problem. I think you have to port the app to sync your data for Linux. Not only that, but I just have that issue in Linux. 
It works fine when I use windows because you have an app to sync your data for windows. 
Also work in android because you have an app for Android.

Great job. Continue doing all of you for this project.

**Comment by ghalfacree** [comment]
I can confirm this bug is still present in v0.2.8 when viewing the user interface on a Linux machine, across all browsers.

**Comment by jerrykuku** [comment]
If this problem still occurs, can you use the F12 key to open debug mode and give me a screenshot of the console message?

**Comment by tigerinus** [comment]
@chicato83  I'm gonna close this issue for now. However if you see this problem happening again, please open a new issue and let the team know. Thanks!
