### ISSUE TITLE
[Alpha][Bug] Cannot import any "Existing Docker Apps" to CasaOS

### ISSUE THREAD

**Issue by AuthorShin** [IceWhaleTech/CasaOS#521]
### What happened?

Cannot import any "Existing Docker Apps" to CasaOS, in fact when clicking on it to import the app to CasaOS it does nothing and it will not popup the importing window.

**Comment by zhanghengxin** [comment]
how much your casaos version?
can you try to update it again?

**Comment by zhanghengxin** [comment]
i have tested it and not found anything which your talk.

**Comment by zhanghengxin** [comment]
this install script has been update

**Comment by AuthorShin** [comment]
<img src="https://i.ibb.co/rQXfZps/Screenshot-2022-09-07-122310.png">

**Comment by zhanghengxin** [comment]
yeah,  you can solve this  problem by re-executing the installation script

**Comment by AuthorShin** [comment]
@zhanghengxin It's the alpha 0.3.6 version.

**Comment by AuthorShin** [comment]
I tried on 2 different systems and it's the same.

**Comment by LinkLeong** [comment]
The problem has been solved, just reinstall 0.3.6

**Comment by AuthorShin** [comment]
I still have this problem, when I want to import an already existing docker app I get this error: `strconv.Atoi: parsing "": invalid syntax`

**Comment by Starstrike** [comment]
This issue is still ongoing in v0.4.13
