### ISSUE TITLE
Editing the Nextcloud config.php in CasaOS changes ownership from "www-data" to "root" [Bug] 

### ISSUE THREAD

**Issue by danieljonce** [IceWhaleTech/CasaOS#829]
**Describe the bug**
After a fresh install of Nextcloud in CasaOS running on Debian everything works as expected until a change is made to config.php using the text editor in CasaOS

**To Reproduce**
1) Install Nextcloud via CasaOS
2) Verify it's working correctly
3) Save a change to the /var/www/config/config.php file using the CasaOS text editor
4) Refresh Nextcloud, it will now throw an error "Cannot write into "config" directory!"

**Expected behavior**
I expect the previous file ownership "www-data www-data" to persist after a file change but it is changed to "root root"

The two ways I've found to work around the issue:

1) Use `chown www-data:www-data var/www/html/config/config.php` from the host OS console (not the Docker container) to change the ownership for config.php back to `www-data www-data`

OR

2) Set the flag `'config_is_read_only' => true,` in the config.php, which works temporarily but during Nextcloud updates the config.php file needs to be writeable.

**Comment by LinkLeong** [comment]
The problem of directory accumulation due to upgrade has been solved in 0.4.2

**Comment by raller1028** [comment]
v0.4.2 has been released, if still have problem please reopen

**Comment by ayon568** [comment]
#nano /config/www/nextcloud/config/config.php
