### ISSUE TITLE
[Alpha][Bug] I hope to increase support for DietPi system

### ISSUE THREAD

**Issue by merlinmxn** [IceWhaleTech/CasaOS#869]
### What happened?

The latest version, on the DietPi system (Debian core), the command line interface cannot be opened normally.

**Comment by merlinmxn** [comment]
Sorry, it has been solved. Just reinstall openssh-server for DietPi.

**Comment by jerrykuku** [comment]
We have been testing with DietPI, if we can't connect to the ssh terminal please try to install open-ssh-server in dietpi. If still have problem please let me know.

**Comment by tigerinus** [comment]
@merlinmxn - what exact is the error message? Can you paste a screenshot?

**Comment by garlik82** [comment]
I'm looking to install casaOS on top of dietpi. I'm just going to backup my setup and try it. I'll report back.

**Comment by jerrykuku** [comment]
If you are referring to the terminal panel of CasaOS, you can first confirm whether the ssh service is enabled. 
This Issue has not been answered for a long time, I will close it, if the problem still exists, you can reopen it.
